CREATE TABLE hosp_data_purview (
    [Provider ID] INT PRIMARY KEY,
    [Hospital Name] VARCHAR(255),
    Address VARCHAR(255),
    City VARCHAR(100),
    State CHAR(2),
    [ZIP Code] VARCHAR(10),
    [County Name] VARCHAR(100),
    [Phone Number] VARCHAR(15),
    [Hospital Type] VARCHAR(100),
    [Hospital Ownership] VARCHAR(100),
    [Emergency Services] BIT,
    [Meets criteria for meaningful use of EHRs] BIT,
    [Hospital overall rating] INT,
    [Hospital overall rating footnote] VARCHAR(255),
    [Mortality national comparison] VARCHAR(255),
    [Mortality national comparison footnote] VARCHAR(255),
    [Safety of care national comparison] VARCHAR(255),
    [Safety of care national comparison footnote] VARCHAR(255),
    [Readmission national comparison] VARCHAR(255),
    [Readmission national comparison footnote] VARCHAR(255),
    [Patient experience national comparison] VARCHAR(255),
    [Patient experience national comparison footnote] VARCHAR(255),
    [Effectiveness of care national comparison] VARCHAR(255),
    [Effectiveness of care national comparison footnote] VARCHAR(255),
    [Timeliness of care national comparison] VARCHAR(255),
    [Timeliness of care national comparison footnote] VARCHAR(255),
    [Efficient use of medical imaging national comparison] VARCHAR(255),
    [Efficient use of medical imaging national comparison footnote] VARCHAR(255),
    Location VARCHAR(255)
);
